name: Package Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Prepare dist directory
        shell: pwsh
        run: |
          if (Test-Path dist) { Remove-Item dist -Recurse -Force }
          New-Item -ItemType Directory -Path dist | Out-Null

      - name: Build Windows executable
        run: npx pkg server.js --targets node18-win-x64 --output dist/server.exe

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-win-x64
          path: dist/server.exe
