name: Pkg Action

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  pkg:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch:
          - x64
        node-version:
          - 20
        os:
          - ubuntu-20.04
          - windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --production
          
      - name: Package into node binary
        uses: lando/pkg-action@v6.0.0
        with:
          entrypoint: server.js
          filename: pda-thing
          arch: ${{ matrix.arch }}
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}
